.TH "hanoi" "6" "2015" "hanoi"
.SH NAME
hanoi - The Towers of Hanoi Game
.SH SYNOPSIS
.TP
.PD
.B hanoi
[-flag]
.PD
.SH DESCRIPTION
.TP
.PD
The object of Towers of Hanoi is to reassemble the left tower's disk over to the right in the correct order. The player enters two numbers. The first number is the disk you wish to move; the second number is the destination of that disk. The lower disks must be greater than the above disk at all times. Only one disk - the highest point of each tower - can be moved at a time. There are three commands available to the player during gameplay:
.B e
or
.B q
to exit the program,
.B m
to abort current game and go to main menu, and
.B u
to undo last move.
.PD
.TP
.PD
.B -h
Show usage information and exit.
.PD
.SH AUTHOR
.TP
.PD
The game hanoi and this manual were written by Luciano D. Cecere <ldante86@aol.com>.
.PD
